// Any copyright is dedicated to the Public Domain.
// http://creativecommons.org/publicdomain/zero/1.0/

/*********************************************
This ambient module example console.logs
ambient light and sound levels and whenever a
specified light or sound level trigger is met.
*********************************************/



// NotificationHub Parameters
var NotificationHubNS = '<your ServiceBus namespace>.servicebus.windows.net'
var hubName = '<Your hub name>'; 
var Key = '<Your SAS Key generated by the SAS tool>';

var tessel = require('tessel');
var ambientlib = require('ambient-attx4');
var https = require('https');

var ambient = ambientlib.use(tessel.port['A']);

ambient.on('ready', function () {
 // Get points of light and sound data.
  setInterval( function () {
    ambient.getLightLevel( function(err, ldata) {
      if (err) throw err;
      ambient.getSoundLevel( function(err, sdata) {
        if (err) throw err;
        console.log("Light level:", ldata.toFixed(8), " ", "Sound Level:", sdata.toFixed(8));
    });
  })}, 500); // The readings will happen every .5 seconds unless the trigger is hit

  ambient.setLightTrigger(0.5);

  // Set a light level trigger
  // The trigger is a float between 0 and 1
  ambient.on('light-trigger', function(data) {
    console.log("Our light trigger was hit:", data);

    // Clear the trigger so it stops firing
    ambient.clearLightTrigger();
    //After 1.5 seconds reset light trigger
    setTimeout(function () {

        ambient.setLightTrigger(0.5);

    },1500);
  });

  // Set a sound level trigger
  // The trigger is a float between 0 and 1
  ambient.setSoundTrigger(0.1);

  ambient.on('sound-trigger', function(data) {
      console.log("Something happened with sound: ", data);
      sendNotificationWP("Something happened with sound");
	  sendNotificationAndroid("Something happened with sound");

    // Clear it
    ambient.clearSoundTrigger();

    //After 1.5 seconds reset sound trigger
    setTimeout(function () {

        ambient.setSoundTrigger(0.1);

    },1500);

  });
});

ambient.on('error', function (err) {
  console.log(err)
});



function sendNotificationWP(message) {

	
    var options = {
        hostname: NotificationHubNS,
        port: 443,
        path: '/' + hubName + '/' + 'messages/' + '?api-version=2013-08',
        method: 'POST',
        headers: {
            'Authorization': Key,
            'Content-Type': 'application/xml;charset=utf-8',
            'ServiceBusNotification-Format' : 'windowsphone', 
			'X-NotificationClass': '2', 
			'X-WindowsPhone-Target': 'toast' 
        }
    };

    var req = https.request(options, function (res) {
        console.log("sendNotificationWP:statusCode: ", res.statusCode);
        console.log("sendNotificationWP:headers: ", res.headers);
		
		res.setEncoding('utf8');
        res.on('data', function (d) {
            
        });
    });

    req.on('error', function (e) {
        console.error(e);
    });
	
	var toast = '<?xml version="1.0" encoding="utf-8"?><wp:Notification xmlns:wp="WPNotification"><wp:Toast><wp:Text1>' + message + '</wp:Text1></wp:Toast></wp:Notification>';   

    req.write(toast);

    req.end();


}

function sendNotificationAndroid(message) {

	
    var options = {
        hostname: NotificationHubNS,
        port: 443,
        path: '/' + hubName + '/' + 'messages/' + '?api-version=2013-08',
        method: 'POST',
        headers: {
            'Authorization': Key,
            'Content-Type': 'application/xml;charset=utf-8',
            'ServiceBusNotification-Format' : 'gcm', 
        }
    };

    var req = https.request(options, function (res) {
        console.log("sendNotificationAndroid:statusCode: ", res.statusCode);
        console.log("sendNotificationAndroid:headers: ", res.headers);	

		res.setEncoding('utf8');
        res.on('data', function (d) {
            
        });
    });

    req.on('error', function (e) {
        console.error(e);
    });
	
	var data = '{"data":{"message":"' + message + '"}}';
	
    req.write(data);

    req.end();


}


